apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  mysql-root-password: aGVsbG8xMjM0Cg== #hello1234
  mysql-user: dXNlcgo= #user
  password: c3VwZXJwdXBlcgo=

  #'wp-user'@'10.110.247.51' 'superpuper'
