apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      hostNetwork: true
      containers:
      - image: wordpress:5.9.0-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: "10.110.247.51"
        - name: DATABASE_USERNAME
          value: "wp-user"
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wp-pv-claim
          mountPath: /var/www/html
      volumes:
      - name: wp-pv-claim
        persistentVolumeClaim:
          claimName: wp-pv-claim
